//  Created Gustavo Garcia Leite on 01/10/19.
//  Copyright © 2019 Gustavo Garcia Leite. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho
//  Component: View -

import UIKit

class CurrencyViewController: UIViewController, CurrencyViewProtocol {

	var presenter: CurrencyPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
