//  Created Gustavo Garcia Leite on 01/10/19.
//  Copyright © 2019 Gustavo Garcia Leite. All rights reserved.
//
//  Template generated by Fauzi Sholichin @fauzisho
//  Component: Presenter -

import UIKit

//MARK: View -
protocol LoginViewProtocol: class {

    var presenter: LoginPresenterProtocol?  { get set }

    func doViewWillAppear()
    /* Presenter -> ViewController */
}

//MARK: Presenter -
protocol LoginPresenterProtocol: class {

    var interactor: LoginInteractorInputProtocol? { get set }
    
    func viewWillAppear()
}

class LoginPresenter: LoginPresenterProtocol {

    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorInputProtocol?
    private let router: LoginRouterProtocol

    init(interface: LoginViewProtocol, interactor: LoginInteractorInputProtocol?, router: LoginRouterProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func viewWillAppear() {
        guard let view = view else { return }
        view.doViewWillAppear()
    }
}

extension LoginPresenter: LoginInteractorOutputProtocol{
    
}
